# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='opera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='未分类', max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('describe', models.CharField(max_length=2000, null=True)),
                ('image', models.BinaryField(max_length=2000, null=True)),
                ('length', models.CharField(max_length=160)),
                ('price', models.CharField(max_length=160)),
                ('status', models.IntegerField(choices=[(1, 'wait'), (2, 'on'), (3, 'down')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=160, null=True)),
                ('money', models.IntegerField()),
                ('data', models.CharField(max_length=160)),
                ('orderlist', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'buy'), (2, 'unbuy')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='schedule1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=200)),
                ('time8_11', models.IntegerField(null=True)),
                ('time12_15', models.IntegerField(null=True)),
                ('time16_19', models.IntegerField(null=True)),
                ('time20_23', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=200)),
                ('time8_11', models.IntegerField(null=True)),
                ('time12_15', models.IntegerField(null=True)),
                ('time16_19', models.IntegerField(null=True)),
                ('time20_23', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=200)),
                ('time8_11', models.IntegerField(null=True)),
                ('time12_15', models.IntegerField(null=True)),
                ('time16_19', models.IntegerField(null=True)),
                ('time20_23', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=200)),
                ('time8_11', models.IntegerField(null=True)),
                ('time12_15', models.IntegerField(null=True)),
                ('time16_19', models.IntegerField(null=True)),
                ('time20_23', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seat1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seat2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seat3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seat4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('play_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opera_id', models.IntegerField()),
                ('studio_id', models.IntegerField()),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'sold'), (2, 'not'), (3, 'wait')], default='2')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=160)),
                ('department', models.IntegerField(choices=[(1, 'manager'), (2, 'employee')])),
            ],
        ),
    ]
