# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yrt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='opera_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='studio_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='studio',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='col',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
