# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yrt', '0004_ticket_operaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opera',
            name='image',
            field=models.ImageField(default='None', null=True, upload_to='img'),
        ),
    ]
